
management.health.rabbit.enabled: false

#### prior to spring 2.4
spring.datasource.url: \${POSTGRES_URL}
spring.datasource.username: \${POSTGRES_USERNAME:}
spring.datasource.password: \${POSTGRES_PASSWORD:}
spring.datasource.hikari.maximumPoolSize: 4
spring.flyway.schemas: \${POSTGRES_SCHEMA:}
spring.flyway.baseline-on-migrate: true
spring.jpa.properties.hibernate.default_schema: \${POSTGRES_SCHEMA:}

spring.cloud.stream.binders.rabbit.type: rabbit
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.host: \${RABBITMQ_HOST}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.port: \${RABBITMQ_PORT:}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.username: \${RABBITMQ_USERNAME:}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.password: \${RABBITMQ_PASSWORD:}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.virtual-host: \${RABBITMQ_VHOST:}

spring:
  application:
    name: scheduler

  cloud:
    stream:
      bindings:

        input:
          destination: scheduler
          group: scheduler_q
          binder: rabbit
          consumer:
            concurrency: 5

      rabbit:
        bindings:
          input:
            consumer:
              bindQueue: true
              bindingRoutingKey: '*.*.scheduler.#'

              deadLetterExchange: fv.dlx
              autoBindDlq: true
              requeueRejected: false
              republishToDlq: true
